#!/bin/Rscript

gender = function(sex) {
  if (sex == "male") {
    s = 5
    return(s)
  }
  if (sex == "female") {
    s = -151
    return(s)
  }
}

scale = function(activity) {
  if (activity == "sedentary") {
    return(1.2)
  }
  if (activity == "lightly") {
    return(1.375)
  }
  if (activity == "moderately") {
    return(1.55)
  }
  if (activity == "active") {
    return(1.725)
  }
  if (activity == "very") {
    return(1.9)
  }
}

# m is mass in kg, h is height in cm, a is age in years,
# s is +5 for males and -151 for females
mifflin = function (mass, height, age, sex) {
  s = gender(sex)
  mifflin = (10 * mass + 6.25 * height - 5 * age) + s
}

TDEE = function (mass) {
  mass = mass * 0.45359237 # convert lbs to kgs
  height = person$height
  age = person$age

  m = mifflin(mass, height, age, person$sex)
  level = scale(person$activity)

  m * level
}

log = function () {
    # get usr input
    cat( "Enter mass in lbs: ")
    m <- readLines("stdin", 1)
    cat("Enter caloric intake for the day: ")
    c <- readLines("stdin", 1)
    d= Sys.Date()
    entry = data.frame (m, c, d)
    # append entry to data csv file
    write.table(entry, file = "data.csv", sep = ",", append = TRUE, quote = FALSE, col.names = FALSE, row.names = FALSE)
    return()
}

macros = function (mass, fat_percent) {
  protein = 1 * mass
  fats = fat_percent * mass
  remaining = (protein * 4) + (fats * 9)
  carbs = remaining/4
  return(list("protein" = protein, "fats" = fats, "carbs" = carbs))
}

check_args = function(args) {
    if (length(args) == 0) { # if no args
      return("Creating plots")
    }
    if (args[1] == "log") { # prompt user
      log()
      return()
    }
    if (args[1] == "TDEE") {
      print("Day TDEE:")
      mass = tail(data[,1], 1) # last recorded mass
      print(TDEE(mass))

      print("Mean TDEE:")
      tdees = mean(TDEE(data[,1]))
      print(mean(tdees))
    }
    if (args[1] == "macros") {
      mass = head(data[,1], 1) # first recorded mass
      mac = macros(mass, 0.4)
      print(mac)
    }
} 

load(file = "person.Rdata")
data = read.csv("data.csv")

args = commandArgs(trailingOnly = TRUE)
check = check_args(args)

vals = seq(1, length(data$mass))

library(ggplot2)

ggplot(data, aes(vals, mass)) +geom_point(aes(colour = calories)) + scale_colour_gradient(trans = 'reverse') + ggtitle("Mass overtime") + xlab("days") + ylab("mass (lbs)")

ggplot(data, aes(vals, mass)) + geom_line(aes(colour = calories)) + scale_colour_gradient(trans = 'reverse') + ggtitle("Mass overtime") + xlab("days") + ylab("mass (lbs)")

ggplot(data, aes(calories, mass)) + geom_line() + ggtitle("Calories vs. Mass") + xlab("calories") + ylab("mass (lbs)")
